AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topics para LocalStack

Resources:
  EmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: EmailTopic

  SmsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SmsTopic

Outputs:
  EmailTopicArn:
    Value: !Ref EmailTopic
    Export:
      Name: EmailTopicArn

  SmsTopicArn:
    Value: !Ref SmsTopic
    Export:
      Name: SmsTopicArn
